"""
✍️ CONTENT AGENT
Content creation, writing, coding, and creative tasks
"""

import asyncio
import logging
from typing import Dict, List, Any
from datetime import datetime

logger = logging.getLogger('ContentAgent')

class ContentAgent:
    """Agent for content creation and writing tasks"""
    
    def __init__(self, agent_id: str, orchestrator, config: Dict):
        self.agent_id = agent_id
        self.orchestrator = orchestrator
        self.config = config
        self.skills = ['write_text', 'write_code', 'edit_text', 'summarize', 'translate', 'creative_write', 'generate_doc']
        
        logger.info(f"✍️ Content Agent initialized: {agent_id}")
    
    async def execute(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Execute content creation task"""
        description = task.get('description', '')
        context = task.get('context', {})
        
        logger.info(f"📝 Creating content: {description[:80]}...")
        
        # Determine content type
        content_type = self._classify_content(description)
        
        try:
            if content_type == 'code':
                result = await self._write_code(description, context)
            elif content_type == 'documentation':
                result = await self._write_documentation(description, context)
            elif content_type == 'creative':
                result = await self._creative_write(description, context)
            elif content_type == 'translation':
                result = await self._translate(description, context)
            elif content_type == 'summary':
                result = await self._summarize(description, context)
            else:
                result = await self._write_text(description, context)
            
            return {
                'success': True,
                'agent': self.agent_id,
                'content_type': content_type,
                'result': result,
                'timestamp': datetime.now().isoformat()
            }
            
        except Exception as e:
            logger.error(f"❌ Content creation failed: {e}")
            return {
                'success': False,
                'agent': self.agent_id,
                'error': str(e)
            }
    
    def _classify_content(self, description: str) -> str:
        """Classify content type from description"""
        desc_lower = description.lower()
        
        if any(w in desc_lower for w in ['code', 'script', 'program', 'function', 'class', 'api']):
            return 'code'
        elif any(w in desc_lower for w in ['doc', 'documentation', 'readme', 'guide', 'manual']):
            return 'documentation'
        elif any(w in desc_lower for w in ['creative', 'story', 'poem', 'artistic', 'fiction']):
            return 'creative'
        elif any(w in desc_lower for w in ['translate', 'translation', 'language']):
            return 'translation'
        elif any(w in desc_lower for w in ['summarize', 'summary', 'tldr', 'brief']):
            return 'summary'
        else:
            return 'text'
    
    async def _write_code(self, description: str, context: Dict) -> Dict:
        """Write code"""
        logger.info(f"💻 Writing code: {description[:50]}")
        
        # Determine language
        languages = {
            'python': 'python',
            'javascript': 'javascript',
            'typescript': 'typescript',
            'bash': 'bash',
            'sql': 'sql',
            'html': 'html',
            'css': 'css',
            'json': 'json',
            'yaml': 'yaml'
        }
        
        detected_lang = 'python'
        for lang, ext in languages.items():
            if lang in description.lower():
                detected_lang = ext
                break
        
        return {
            'type': 'code',
            'language': detected_lang,
            'code': f'# Code for: {description}\n# Generated by ContentAgent\n\nprint("Hello World")',
            'explanation': 'Code explanation here',
            'usage': 'How to use this code',
            'dependencies': []
        }
    
    async def _write_documentation(self, description: str, context: Dict) -> Dict:
        """Write documentation"""
        logger.info(f"📖 Writing documentation: {description[:50]}")
        
        return {
            'type': 'documentation',
            'title': f'Documentation: {description[:50]}',
            'sections': [
                {'heading': 'Overview', 'content': '...'},
                {'heading': 'Installation', 'content': '...'},
                {'heading': 'Usage', 'content': '...'},
                {'heading': 'API Reference', 'content': '...'},
                {'heading': 'Examples', 'content': '...'},
            ],
            'format': 'markdown'
        }
    
    async def _creative_write(self, description: str, context: Dict) -> Dict:
        """Creative writing"""
        logger.info(f"🎨 Creative writing: {description[:50]}")
        
        return {
            'type': 'creative',
            'content': f'Creative content for: {description}',
            'style': 'engaging',
            'tone': 'professional',
            'word_count': 500
        }
    
    async def _translate(self, description: str, context: Dict) -> Dict:
        """Translate content"""
        logger.info(f"🌐 Translating: {description[:50]}")
        
        # Detect target language
        languages = ['greek', 'english', 'spanish', 'french', 'german', 'chinese', 'japanese', 'russian']
        target_lang = 'english'
        
        for lang in languages:
            if lang in description.lower():
                target_lang = lang
                break
        
        return {
            'type': 'translation',
            'target_language': target_lang,
            'original': description,
            'translated': f'Translated to {target_lang}: {description}',
            'confidence': 0.95
        }
    
    async def _summarize(self, description: str, context: Dict) -> Dict:
        """Summarize content"""
        logger.info(f"📋 Summarizing: {description[:50]}")
        
        return {
            'type': 'summary',
            'original_length': len(description),
            'summary': f'Summary of: {description[:100]}...',
            'key_points': ['Key point 1', 'Key point 2', 'Key point 3'],
            'reduction_ratio': 0.3
        }
    
    async def _write_text(self, description: str, context: Dict) -> Dict:
        """General text writing"""
        logger.info(f"📝 Writing text: {description[:50]}")
        
        return {
            'type': 'text',
            'content': f'Content for: {description}',
            'format': 'plain_text',
            'tone': 'professional',
            'length': 'medium'
        }
    
    async def cleanup(self):
        """Cleanup agent resources"""
        logger.info(f"🧹 Content Agent cleanup: {self.agent_id}")


if __name__ == '__main__':
    agent = ContentAgent('test_content', None, {})
    result = asyncio.run(agent.execute({
        'description': 'Write a Python function to calculate fibonacci',
        'context': {}
    }))
    print(result)
